CREATE DATABASE db_tienda_usuarios;
CREATE TABLE USUARIO(
    CEDULA_USUARIO INT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(255) NOT NULL,
    DIRECCION_USUARIO VARCHAR(255) NOT NULL,
    EMAIL_USUARIO VARCHAR(255) NOT NULL,
    TELEFONO_USUARIO VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

--============= Base de datos Clientes.
CREATE DATABASE db_tienda_clientes;
CREATE TABLE CLIENTE(
    CEDULA_CLIENTE INT PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR(255) NOT NULL,
    DIRECCION_CLIENTE VARCHAR(255) NOT NULL,
    EMAIL_CLIENTE VARCHAR(255) NOT NULL,
    TELEFONO_CLIENTE VARCHAR(255) NOT NULL
);

--============= Base de datos proveedores.
CREATE DATABASE db_tienda_proveedores;
CREATE TABLE PROVEEDOR(
    NITPROVEEDOR INT PRIMARY KEY,
    NOMBRE_PROVEEDOR VARCHAR(255) NOT NULL,
    DIRECCION_PROVEEDOR VARCHAR(255) NOT NULL,
    TELEFONO_PROVEEDOR VARCHAR(255) NOT NULL,
    CIUDAD_PROVEEDOR VARCHAR(255) NOT NULL
);

--============= Base de datos productos.
CREATE DATABASE db_tienda_productos;
CREATE TABLE PRODUCTO(
    CODIGO_PRODUCTO INT PRIMARY KEY,
    NITPROVEEDOR INT NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(255) NOT NULL,
    PRECIO_COMPRA INT NOT NULL,
    PRECIO_VENTA INT NOT NULL,
    IVACOMPRA INT NOT NULL
);

--============= Base de datos ventas y detalle.
CREATE DATABASE db_tienda_ventas;

CREATE TABLE VENTA(
    CODIGO_VENTA SERIAL PRIMARY KEY, -- Usamos SERIAL para autoincrement en Postgres
    CEDULA_CLIENTE INT NOT NULL, -- Relación lógica con MS-Clientes
    CEDULA_USUARIO INT NOT NULL, -- Relación lógica con MS-Usuarios
    IVAVENTA INT NOT NULL,
    VALOR_VENTA INT NOT NULL,
    TOTAL_VENTA INT NOT NULL
);

CREATE TABLE DETALLE_VENTA(
    CODIGO_DETALLE_VENTA SERIAL PRIMARY KEY,
    CODIGO_PRODUCTO INT NOT NULL, -- Relación lógica con MS-Productos
    CODIGO_VENTA INT NOT NULL,
    CANTIDAD_PRODUCTO INT,
    VALOR_TOTAL INT NOT NULL,
    VALOR_VENTA INT NOT NULL,
    VALORIVA INT NOT NULL,
    CONSTRAINT fk_venta FOREIGN KEY (CODIGO_VENTA) REFERENCES VENTA(CODIGO_VENTA)
);