spring.application.name=ms-proveedores
server.port=8083

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/db_tienda_proveedores?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=Admin2025

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=ms-proveedores