spring.application.name=ms-ventas
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/db_tienda_ventas?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update