spring.application.name=ms-usuarios

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=${EUREKA_URL}

eureka.instance.prefer-ip-address=true
