spring.application.name=ms-clientes
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/db_tienda_clientes?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

