spring.application.name=ms-clientes
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/db_tienda_clientes?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=Admin2025

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/